### ISSUE TITLE
Paint and fStacks

### ISSUE THREAD

**Issue by AuroreFMN** [kkapsner/Matlab#3]
when painting a region of a tif stack to get the fluorescence info, this line is not working : 

"fStack = tracking.fluoStacks{1}{1};"
![bildschirmfoto 2015-04-07 um 09 21 14](https://cloud.githubusercontent.com/assets/10435329/7018650/84bbcf16-dd07-11e4-8e66-c1e585ffe48b.png)
And I'm not sure how to procede from there, especially when I have several painted regions of interest to analyze.

**Comment by kkapsner** [comment]
Your variable is called "var" and not "tracking".
