### ISSUE TITLE
why 1/12 is the normalized second central moment of a pixel with unit length.

### ISSUE THREAD

**Issue by qxcs** [kkapsner/Matlab#4]
in  Matlab/classes/@ROI/calculateEllipse.m line 26,how 1/12 comes?

**Comment by kkapsner** [comment]
The second central moment in 2D is defined as 
![grafik](https://user-images.githubusercontent.com/1105157/44482771-9ce6e080-a649-11e8-9ace-f55721e621d4.png)

This gives for a unit pixel 
![grafik](https://user-images.githubusercontent.com/1105157/44482797-a96b3900-a649-11e8-9fce-929da326bd12.png)
